export const menuItems = {
  message: {
    pages: [
      {
        name: "Recruitment",
        title: "Recruitment",
        for_user: "",
        parent_page: "HR",
        content:
          '[{"id":"5vtWWuFVl5","type":"chart","data":{"chart_name":"Department Wise Openings","col":12}},{"id":"ZEoAw35RfK","type":"spacer","data":{"col":12}},{"id":"xepXoykemN","type":"header","data":{"text":"<span class=\\"h4\\"><b>Your Shortcuts</b></span>","col":12}},{"id":"LMnFL-FVNb","type":"shortcut","data":{"shortcut_name":"Job Opening","col":3}},{"id":"BOczA5gAXn","type":"shortcut","data":{"shortcut_name":"Job Applicant","col":3}},{"id":"h6LkcOPQpV","type":"shortcut","data":{"shortcut_name":"Job Offer","col":3}},{"id":"TrRgFLeATn","type":"shortcut","data":{"shortcut_name":"Dashboard","col":3}},{"id":"VqqHZk5Ymw","type":"spacer","data":{"col":12}},{"id":"B0A1wqOP8R","type":"quick_list","data":{"quick_list_name":"Interviews (This Week)","col":6}},{"id":"BSfCSxeOZN","type":"spacer","data":{"col":12}},{"id":"ouzRaGAJJl","type":"header","data":{"text":"<span class=\\"h4\\"><b>Masters &amp; Reports</b></span>","col":12}},{"id":"0akZyj1E4k","type":"card","data":{"card_name":"Jobs","col":4}},{"id":"3Q-ITUYR-W","type":"card","data":{"card_name":"Interviews","col":4}},{"id":"06gIuB5svR","type":"card","data":{"card_name":"Appointment","col":4}},{"id":"Q4msp7F8vF","type":"card","data":{"card_name":"Reports","col":4}}]',
        public: 1,
        module: "HR",
        icon: "users",
        is_hidden: 0,
        label: "Recruitment",
      },
      {
        name: "Build",
        title: "Build",
        for_user: "",
        parent_page: "",
        content:
          '[{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Your Shortcuts</b></span>","col":12}},{"type":"shortcut","data":{"shortcut_name":"DocType","col":3}},{"type":"shortcut","data":{"shortcut_name":"Workspace","col":3}},{"type":"shortcut","data":{"shortcut_name":"Report","col":3}},{"type":"spacer","data":{"col":12}},{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Elements</b></span>","col":12}},{"type":"card","data":{"card_name":"Modules","col":4}},{"type":"card","data":{"card_name":"Models","col":4}},{"type":"card","data":{"card_name":"Views","col":4}},{"type":"card","data":{"card_name":"Scripting","col":4}},{"type":"card","data":{"card_name":"Packages","col":4}},{"type":"card","data":{"card_name":"System Logs","col":4}}]',
        public: 1,
        module: "Core",
        icon: "tool",
        is_hidden: 0,
        label: "Build",
      },
      {
        name: "Employee Lifecycle",
        title: "Employee Lifecycle",
        for_user: "",
        parent_page: "HR",
        content:
          '[{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Your Shortcuts</b></span>","col":12}},{"type":"shortcut","data":{"shortcut_name":"Employee Onboarding","col":3}},{"type":"shortcut","data":{"shortcut_name":"Employee Separation","col":3}},{"type":"shortcut","data":{"shortcut_name":"Employee Grievance","col":3}},{"type":"shortcut","data":{"shortcut_name":"Dashboard","col":3}},{"type":"spacer","data":{"col":12}},{"type":"quick_list","data":{"quick_list_name":"New Hires (This Month)","col":4}},{"type":"quick_list","data":{"quick_list_name":"Exits (This Month)","col":4}},{"type":"quick_list","data":{"quick_list_name":"Trainings (This Week)","col":4}},{"type":"spacer","data":{"col":12}},{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Masters &amp; Reports</b></span>","col":12}},{"type":"card","data":{"card_name":"Onboarding","col":4}},{"type":"card","data":{"card_name":"Journey","col":4}},{"type":"card","data":{"card_name":"Grievance","col":4}},{"type":"card","data":{"card_name":"Training","col":4}},{"type":"card","data":{"card_name":"Exit","col":4}},{"type":"card","data":{"card_name":"Daily Work Summary","col":4}},{"type":"card","data":{"card_name":"Reports","col":4}}]',
        public: 1,
        module: "HR",
        icon: "assign",
        is_hidden: 0,
        label: "Employee Lifecycle",
      },
      {
        name: "Performance",
        title: "Performance",
        for_user: "",
        parent_page: "HR",
        content:
          '[{"id":"nZ9MUieUjy","type":"header","data":{"text":"<span class=\\"h4\\"><b>Your Shortcuts</b></span>","col":12}},{"id":"ETYoHfg2k0","type":"shortcut","data":{"shortcut_name":"Appraisal","col":3}},{"id":"VRnsImMEoD","type":"shortcut","data":{"shortcut_name":"Employee Performance Feedback","col":5}},{"id":"vXBMJGJ98C","type":"shortcut","data":{"shortcut_name":"Goal","col":3}},{"id":"Vtre-LDhRc","type":"spacer","data":{"col":12}},{"id":"NmUDJB28UL","type":"header","data":{"text":"<span class=\\"h4\\"><b>Masters &amp; Transactions</b></span>","col":12}},{"id":"vNnUr6yHsH","type":"card","data":{"card_name":"Masters","col":4}},{"id":"v8mC6C_9V-","type":"card","data":{"card_name":"Appraisal","col":4}},{"id":"8X_kx16fax","type":"card","data":{"card_name":"Energy Points","col":4}},{"id":"x_fx5yusAz","type":"card","data":{"card_name":"Promotion","col":4}},{"id":"ofPrShxelC","type":"card","data":{"card_name":"Reports","col":4}}]',
        public: 1,
        module: "HR",
        icon: "star",
        is_hidden: 0,
        label: "Performance",
      },
      {
        name: "Shift & Attendance",
        title: "Shift & Attendance",
        for_user: "",
        parent_page: "HR",
        content:
          '[{"type":"chart","data":{"chart_name":"Attendance Count","col":12}},{"type":"spacer","data":{"col":12}},{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Your Shortcuts</b></span>","col":12}},{"type":"shortcut","data":{"shortcut_name":"Employee Checkin","col":3}},{"type":"shortcut","data":{"shortcut_name":"Attendance","col":3}},{"type":"shortcut","data":{"shortcut_name":"Shift Request","col":3}},{"type":"shortcut","data":{"shortcut_name":"Dashboard","col":3}},{"type":"spacer","data":{"col":12}},{"type":"header","data":{"text":"<span style=\\"font-size: 18px;\\"><b>Masters &amp; Reports</b></span>","col":12}},{"type":"card","data":{"card_name":"Shifts","col":4}},{"type":"card","data":{"card_name":"Attendance","col":4}},{"type":"card","data":{"card_name":"Time","col":4}},{"type":"card","data":{"card_name":"Reports","col":4}}]',
        public: 1,
        module: "HR",
        icon: "milestone",
        is_hidden: 0,
        label: "Shift & Attendance",
      },
      {
        name: "HR",
        title: "HR",
        for_user: "",
        parent_page: "",
        content:
          '[{"type":"onboarding","data":{"onboarding_name":"Human Resource","col":12}},{"type":"chart","data":{"chart_name":"Hiring vs Attrition Count","col":12}},{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Your Shortcuts</b></span>","col":12}},{"type":"shortcut","data":{"shortcut_name":"Employee","col":3}},{"type":"shortcut","data":{"shortcut_name":"Leave Application","col":3}},{"type":"shortcut","data":{"shortcut_name":"HR Dashboard","col":3}},{"type":"shortcut","data":{"shortcut_name":"Recruitment Dashboard","col":3}},{"type":"shortcut","data":{"shortcut_name":"Employee Lifecycle Dashboard","col":3}},{"type":"shortcut","data":{"shortcut_name":"Attendance Dashboard","col":3}},{"type":"shortcut","data":{"shortcut_name":"Expense Claims Dashboard","col":3}},{"type":"spacer","data":{"col":12}},{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Reports &amp; Masters</b></span>","col":12}},{"type":"card","data":{"card_name":"Setup","col":4}},{"type":"card","data":{"card_name":"Employee","col":4}},{"type":"card","data":{"card_name":"Leaves","col":4}},{"type":"card","data":{"card_name":"Settings","col":4}},{"type":"card","data":{"card_name":"Attendance","col":4}},{"type":"card","data":{"card_name":"Expense Claim","col":4}},{"type":"card","data":{"card_name":"Key Reports","col":4}},{"type":"card","data":{"card_name":"Other Reports","col":4}}]',
        public: 1,
        module: "HR",
        icon: "hr",
        is_hidden: 0,
        label: "HR",
      },
      {
        name: "Customization",
        title: "Customization",
        for_user: "",
        parent_page: "",
        content:
          '[{"type":"onboarding","data":{"onboarding_name":"Customization","col":12}},{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Your Shortcuts</b></span>","col":12}},{"type":"shortcut","data":{"shortcut_name":"Customize Form","col":3}},{"type":"shortcut","data":{"shortcut_name":"Custom Role","col":3}},{"type":"shortcut","data":{"shortcut_name":"Client Script","col":3}},{"type":"shortcut","data":{"shortcut_name":"Server Script","col":3}},{"type":"spacer","data":{"col":12}},{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Reports &amp; Masters</b></span>","col":12}},{"type":"card","data":{"card_name":"Dashboards","col":4}},{"type":"card","data":{"card_name":"Form Customization","col":4}},{"type":"card","data":{"card_name":"Other","col":4}}]',
        public: 1,
        module: "Custom",
        icon: "customization",
        is_hidden: 0,
        label: "Customization",
      },
      {
        name: "Expense Claims",
        title: "Expense Claims",
        for_user: "",
        parent_page: "HR",
        content:
          '[{"type":"chart","data":{"chart_name":"Expense Claims","col":12}},{"type":"spacer","data":{"col":12}},{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Your Shortcuts</b></span>","col":12}},{"type":"shortcut","data":{"shortcut_name":"Expense Claim","col":3}},{"type":"shortcut","data":{"shortcut_name":"Employee Advance","col":3}},{"type":"shortcut","data":{"shortcut_name":"Dashboard","col":3}},{"type":"spacer","data":{"col":12}},{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Masters &amp; Reports</b></span>","col":12}},{"type":"card","data":{"card_name":"Claims","col":4}},{"type":"card","data":{"card_name":"Advances","col":4}},{"type":"card","data":{"card_name":"Fleet Management","col":4}},{"type":"card","data":{"card_name":"Travel","col":4}},{"type":"card","data":{"card_name":"Reports","col":4}},{"type":"card","data":{"card_name":"Accounting Reports","col":4}}]',
        public: 1,
        module: "HR",
        icon: "expenses",
        is_hidden: 0,
        label: "Expense Claims",
      },
      {
        name: "Salary Payout",
        title: "Salary Payout",
        for_user: "",
        parent_page: "Payroll",
        content:
          '[{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Your Shortcuts</b></span>","col":12}},{"type":"shortcut","data":{"shortcut_name":"Salary Slip","col":3}},{"type":"shortcut","data":{"shortcut_name":"Payroll Entry","col":3}},{"type":"shortcut","data":{"shortcut_name":"Salary Register","col":3}},{"type":"spacer","data":{"col":12}},{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Transactions &amp; Reports</b></span>","col":12}},{"type":"card","data":{"card_name":"Masters","col":4}},{"type":"card","data":{"card_name":"Payroll","col":4}},{"type":"card","data":{"card_name":"Incentives","col":4}},{"type":"card","data":{"card_name":"Loans","col":4}},{"type":"card","data":{"card_name":"Accounting","col":4}},{"type":"card","data":{"card_name":"Accounting Reports","col":4}},{"type":"card","data":{"card_name":"Payroll Reports","col":4}},{"type":"card","data":{"card_name":"Deduction Reports","col":4}}]',
        public: 1,
        module: "Payroll",
        icon: "income",
        is_hidden: 0,
        label: "Salary Payout",
      },
      {
        name: "Projects",
        title: "Projects",
        for_user: "",
        parent_page: "",
        content:
          '[{"type":"chart","data":{"chart_name":"Open Projects","col":12}},{"type":"spacer","data":{"col":12}},{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Your Shortcuts</b></span>","col":12}},{"type":"shortcut","data":{"shortcut_name":"Task","col":3}},{"type":"shortcut","data":{"shortcut_name":"Project","col":3}},{"type":"shortcut","data":{"shortcut_name":"Timesheet","col":3}},{"type":"shortcut","data":{"shortcut_name":"Project Billing Summary","col":3}},{"type":"shortcut","data":{"shortcut_name":"Dashboard","col":3}},{"type":"spacer","data":{"col":12}},{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Reports &amp; Masters</b></span>","col":12}},{"type":"card","data":{"card_name":"Projects","col":4}},{"type":"card","data":{"card_name":"Time Tracking","col":4}},{"type":"card","data":{"card_name":"Reports","col":4}},{"type":"card","data":{"card_name":"Settings","col":4}}]',
        public: 1,
        module: "Projects",
        icon: "project",
        is_hidden: 0,
        label: "Projects",
      },
      {
        name: "Leaves",
        title: "Leaves",
        for_user: "",
        parent_page: "HR",
        content:
          '[{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Your Shortcuts</b></span>","col":12}},{"type":"shortcut","data":{"shortcut_name":"Leave Application","col":3}},{"type":"shortcut","data":{"shortcut_name":"Leave Allocation","col":3}},{"type":"spacer","data":{"col":12}},{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Masters &amp; Reports</b></span>","col":12}},{"type":"card","data":{"card_name":"Setup","col":4}},{"type":"card","data":{"card_name":"Allocation","col":4}},{"type":"card","data":{"card_name":"Application","col":4}},{"type":"card","data":{"card_name":"Reports","col":4}}]',
        public: 1,
        module: "HR",
        icon: "non-profit",
        is_hidden: 0,
        label: "Leaves",
      },
      {
        name: "Payroll",
        title: "Payroll",
        for_user: "",
        parent_page: "",
        content:
          '[{"type":"onboarding","data":{"onboarding_name":"Payroll","col":12}},{"type":"chart","data":{"chart_name":"Outgoing Salary","col":12}},{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Your Shortcuts</b></span>","col":12}},{"type":"shortcut","data":{"shortcut_name":"Dashboard","col":3}},{"type":"shortcut","data":{"shortcut_name":"Salary Register","col":3}},{"type":"spacer","data":{"col":12}},{"type":"card","data":{"card_name":"Quick Links","col":4}},{"type":"card","data":{"card_name":"Settings","col":4}}]',
        public: 1,
        module: "Payroll",
        icon: "money-coins-1",
        is_hidden: 0,
        label: "Payroll",
      },
      {
        name: "Integrations",
        title: "Integrations",
        for_user: "",
        parent_page: "",
        content:
          '[{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Reports &amp; Masters</b></span>","col":12}},{"type":"card","data":{"card_name":"Backup","col":4}},{"type":"card","data":{"card_name":"Google Services","col":4}},{"type":"card","data":{"card_name":"Authentication","col":4}},{"type":"card","data":{"card_name":"Settings","col":4}}]',
        public: 1,
        module: "Integrations",
        icon: "integration",
        is_hidden: 0,
        label: "Integrations",
      },
      {
        name: "Tools",
        title: "Tools",
        for_user: "",
        parent_page: "",
        content:
          '[{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Your Shortcuts</b></span>","col":12}},{"type":"shortcut","data":{"shortcut_name":"ToDo","col":3}},{"type":"shortcut","data":{"shortcut_name":"Note","col":3}},{"type":"shortcut","data":{"shortcut_name":"File","col":3}},{"type":"shortcut","data":{"shortcut_name":"Assignment Rule","col":3}},{"type":"shortcut","data":{"shortcut_name":"Auto Repeat","col":3}},{"type":"spacer","data":{"col":12}},{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Reports & Masters</b></span>","col":12}},{"type":"card","data":{"card_name":"Tools","col":4}},{"type":"card","data":{"card_name":"Email","col":4}},{"type":"card","data":{"card_name":"Automation","col":4}},{"type":"card","data":{"card_name":"Event Streaming","col":4}}]',
        public: 1,
        module: "Automation",
        icon: "tool",
        is_hidden: 0,
        label: "Tools",
      },
      {
        name: "Users",
        title: "Users",
        for_user: "",
        parent_page: "",
        content:
          '[{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Your Shortcuts</b></span>","col":12}},{"type":"shortcut","data":{"shortcut_name":"User","col":3}},{"type":"shortcut","data":{"shortcut_name":"Role","col":3}},{"type":"shortcut","data":{"shortcut_name":"Permission Manager","col":3}},{"type":"shortcut","data":{"shortcut_name":"User Profile","col":3}},{"type":"shortcut","data":{"shortcut_name":"User Type","col":3}},{"type":"spacer","data":{"col":12}},{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Reports & Masters</b></span>","col":12}},{"type":"card","data":{"card_name":"Users","col":4}},{"type":"card","data":{"card_name":"Logs","col":4}},{"type":"card","data":{"card_name":"Permissions","col":4}}]',
        public: 1,
        module: "Core",
        icon: "users",
        is_hidden: 0,
        label: "Users",
      },
      {
        name: "Website",
        title: "Website",
        for_user: "",
        parent_page: "",
        content:
          '[{"type":"onboarding","data":{"onboarding_name":"Website","col":12}},{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Your Shortcuts</b></span>","col":12}},{"type":"shortcut","data":{"shortcut_name":"Blog Post","col":3}},{"type":"shortcut","data":{"shortcut_name":"Blogger","col":3}},{"type":"shortcut","data":{"shortcut_name":"Web Page","col":3}},{"type":"shortcut","data":{"shortcut_name":"Web Form","col":3}},{"type":"shortcut","data":{"shortcut_name":"Website Settings","col":3}},{"type":"spacer","data":{"col":12}},{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Reports & Masters</b></span>","col":12}},{"type":"card","data":{"card_name":"Setup","col":4}},{"type":"card","data":{"card_name":"Blog","col":4}},{"type":"card","data":{"card_name":"Web Site","col":4}},{"type":"card","data":{"card_name":"Portal","col":4}},{"type":"card","data":{"card_name":"Knowledge Base","col":4}}]',
        public: 1,
        module: "Website",
        icon: "website",
        is_hidden: 0,
        label: "Website",
      },
      {
        name: "Tax & Benefits",
        title: "Tax & Benefits",
        for_user: "",
        parent_page: "Payroll",
        content:
          '[{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Your Shortcuts</b></span>","col":12}},{"type":"shortcut","data":{"shortcut_name":"Employee Tax Exemption Declaration","col":3}},{"type":"shortcut","data":{"shortcut_name":"Additional Salary","col":3}},{"type":"shortcut","data":{"shortcut_name":"Income Tax Computation","col":3}},{"type":"spacer","data":{"col":12}},{"type":"header","data":{"text":"<span class=\\"h4\\"><b>Masters &amp; Reports</b></span>","col":12}},{"type":"card","data":{"card_name":"Tax Setup","col":4}},{"type":"card","data":{"card_name":"Exemption","col":4}},{"type":"card","data":{"card_name":"Benefits","col":4}},{"type":"card","data":{"card_name":"Reports","col":4}}]',
        public: 1,
        module: "Payroll",
        icon: "crm",
        is_hidden: 0,
        label: "Tax & Benefits",
      },
    ],
    has_access: true,
  },
};
